# Generated by Django 3.1.5 on 2021-03-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Team_Member',
        ),
    ]
