# Generated by Django 3.1.5 on 2021-03-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapper', '0002_auto_20210313_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='rapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('date_of_born', models.DateField()),
                ('place_of_born', models.CharField(max_length=100)),
                ('about_him', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('rapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapper.rapper', verbose_name='rapper')),
            ],
        ),
    ]
