# Generated by Django 3.1.5 on 2021-03-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapper', '0003_music_rapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapper',
            name='anghami',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='deezer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='instgram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='spotify',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rapper',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
