# Generated by Django 3.1.5 on 2021-03-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapper', '0004_auto_20210313_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapper',
            name='about_him',
            field=models.TextField(max_length=1000),
        ),
    ]
