# Generated by Django 3.1.7 on 2021-03-13 20:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapper', '0005_auto_20210313_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapper',
            name='about_him',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
