# Generated by Django 3.1.7 on 2021-03-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapper', '0011_auto_20210315_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community_post',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='community_post',
        ),
    ]
