# Generated by Django 3.1.7 on 2021-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210315_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_post',
            name='visable',
            field=models.BooleanField(default=False),
        ),
    ]
